namespace MAKER.AI.Models
{
    /// <summary>
    /// Represents a response received from an AI model, including the generated content and token usage statistics.
    /// </summary>
    public class AIResponse
    {
        /// <summary>
        /// Gets the text content returned by the AI model. May be <c>null</c> if the model produced no output.
        /// </summary>
        public string? Content { get; init; }

        /// <summary>
        /// Gets the number of tokens consumed by the input prompt sent to the AI model.
        /// </summary>
        public int InputTokens { get; init; }

        /// <summary>
        /// Gets the number of tokens generated by the AI model in its response.
        /// </summary>
        public int OutputTokens { get; init; }

        /// <summary>
        /// Initializes a new instance of the <see cref="AIResponse"/> class.
        /// </summary>
        public AIResponse() { }
    }
}
